CREATE DATABASE CentroMedicoRASA

USE CentroMedicoRASA

--CREACIÓN DE LAS TABLAS
CREATE TABLE PACIENTE (
  Id_paciente		INT IDENTITY (1,1) NOT NULL PRIMARY KEY, 
  Nombre			VARCHAR (20) NOT NULL,
  Apellido_Paterno	VARCHAR (20) NOT NULL,
  Apellido_Materno	VARCHAR (20),
  Curp				VARCHAR (20) NOT NULL,
  Telefono			VARCHAR (10)
)

CREATE TABLE HISTORIA_MEDICO (
  Id_historial	INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Id_paciente	INT NOT NULL,
  Tipo_sangre	VARCHAR (10),
  Estatura		DECIMAL,
  Peso			DECIMAL,
  Edad			INT, 
  Alergias		VARCHAR (200)
)

CREATE TABLE MEDICAMENTO (
  Id_medicamento	INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Nombre			VARCHAR (20) NOT NULL,
  Descripcion		VARCHAR (20),
  Concentracion		VARCHAR (20),
  Precio			MONEY
)

CREATE TABLE ALMACEN (
  Id_Almacen		INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Id_medicamento	INT NOT NULL,
  Existencias		INT,
  Tipo				VARCHAR (20)
)

CREATE TABLE EMPLEADO (
  Id_empleado	INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Nombre				VARCHAR (20) NOT NULL,
  Tipo_empleo			VARCHAR (20),
  Curp					VARCHAR (20) NOT NULL,
  Correo				VARCHAR (20),
  Telefono				VARCHAR (20),
  Fecha_contratacion	DATE,
)

CREATE TABLE ESPECIALIDAD (
  Id_especialidad	INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Nombre			VARCHAR (30) NOT NULL,
)

CREATE TABLE HORARIO (
  Id_Horario	INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Hora_Inicio	TIME NOT NULL,
  Hora_Fin		TIME NOT NULL,
)

CREATE TABLE DOCTOR (
  Id_doctor			INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Id_empleado		INT NOT NULL,
  Id_especialidad	INT NOT NULL,
  Id_Horario		INT NOT NULL
)

CREATE TABLE RECEPCIONISTA (
  Id_Recepcionista	INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Id_empleado		INT NOT NULL,
  Hora_Inicio		TIME NOT NULL,
  Hora_Fin			TIME NOT NULL
)

CREATE TABLE CONSULTORIO (
  Id_consultorio	INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Id_Doctor			INT NOT NULL,
  Numero			INT,
  Piso				INT
)

CREATE TABLE RECETA (
  Id_receta		INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Id_paciente	INT NOT NULL,
  Id_doctor		INT NOT NULL,
  Fecha			DATE NOT NULL,
  Diagnostico	VARCHAR (30) NOT NULL,
  Tratamiento	VARCHAR (30)
)

CREATE TABLE RECETA_MEDICINA (
  Id_receta			INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Id_medicamento	INT NOT NULL,
  Dosis				DECIMAL NOT NULL,
  Frecuencia		VARCHAR (10) NOT NULL,
  Indicaciones		VARCHAR (10) NOT NULL
)

CREATE TABLE SERVICIO (
  Id_servicio	INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Nombre		VARCHAR (20),
  Costo			DECIMAL,
  Descripcion	VARCHAR (30)
)

CREATE TABLE CITA (
  Id_cita			INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Id_paciente		INT NOT NULL,
  Id_doctor			INT NOT NULL,
  Id_consultorio	INT NOT NULL,
  Id_receta			INT NOT NULL,
  Fecha_cita		DATE NOT NULL,
  hora_cita			TIME NOT NULL,
  Dia				INT NOT NULL,
  Mes				INT NOT NULL,
  Estatus			BIT  NOT NULL
)

CREATE TABLE CITA_SERVICIO (
  Id_cita		INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Id_servicio	INT NOT NULL,
  Cantidad		INT NOT NULL,
  Subtotal		DECIMAL NOT NULL
)

CREATE TABLE PAGO (
  Id_pago		INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Id_cita		INT NOT NULL,
  Id_Doctor		INT NOT NULL,
  Monto			DECIMAL NOT NULL,
  Fecha_pago	DATE NOT NULL,
  Estatus		BIT NOT NULL,
  Linea_pago	VARCHAR (20) NOT NULL
)

CREATE TABLE BITACORA_CITA (
  Id_bitacora		INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Id_cita			INT NOT NULL,
  Id_Recepcionista	INT NOT NULL,
  Estatus_cita		BIT NOT NULL,
  Monto_devuelto	DECIMAL NOT NULL,
  Inicio			TIME NOT NULL,
  Fin				TIME NOT NULL
)

--CONEXIÓN ENTRE LLAVES FORANEAS
--HISTORIA_MEDICO → PACIENTE
ALTER TABLE HISTORIA_MEDICO
ADD FOREIGN KEY (Id_paciente) REFERENCES PACIENTE(Id_paciente)

--ALMACEN → MEDICAMENTO
ALTER TABLE ALMACEN
ADD FOREIGN KEY (Id_medicamento) REFERENCES MEDICAMENTO(Id_medicamento)

-- DOCTOR → EMPLEADO
ALTER TABLE DOCTOR
ADD FOREIGN KEY (Id_empleado) REFERENCES EMPLEADO(Id_empleado)

-- DOCTOR → ESPECIALIDAD
ALTER TABLE DOCTOR
ADD FOREIGN KEY (Id_especialidad) REFERENCES ESPECIALIDAD(Id_especialidad)

-- DOCTOR → HORARIO
ALTER TABLE DOCTOR
ADD FOREIGN KEY (Id_Horario) REFERENCES HORARIO(Id_Horario)

-- RECEPCIONISTA → EMPLEADO
ALTER TABLE RECEPCIONISTA
ADD FOREIGN KEY (Id_empleado) REFERENCES EMPLEADO(Id_empleado)

-- CONSULTORIO → DOCTOR
ALTER TABLE CONSULTORIO
ADD FOREIGN KEY (Id_Doctor) REFERENCES DOCTOR(Id_doctor)

-- RECETA → PACIENTE
ALTER TABLE RECETA
ADD FOREIGN KEY (Id_paciente) REFERENCES PACIENTE(Id_paciente)

-- RECETA → DOCTOR
ALTER TABLE RECETA
ADD FOREIGN KEY (Id_doctor) REFERENCES DOCTOR(Id_doctor)

-- RECETA_MEDICINA → RECETA
ALTER TABLE RECETA_MEDICINA
ADD FOREIGN KEY (Id_receta) REFERENCES RECETA(Id_receta)

-- RECETA_MEDICINA → MEDICAMENTO
ALTER TABLE RECETA_MEDICINA
ADD FOREIGN KEY (Id_medicamento) REFERENCES MEDICAMENTO(Id_medicamento)

-- CITA → PACIENTE
ALTER TABLE CITA
ADD FOREIGN KEY (Id_paciente) REFERENCES PACIENTE(Id_paciente)

-- CITA → DOCTOR
ALTER TABLE CITA
ADD FOREIGN KEY (Id_doctor) REFERENCES DOCTOR(Id_doctor)

-- CITA → CONSULTORIO
ALTER TABLE CITA
ADD FOREIGN KEY (Id_consultorio) REFERENCES CONSULTORIO(Id_consultorio)

-- CITA → RECETA 
ALTER TABLE CITA
ADD FOREIGN KEY (Id_receta) REFERENCES RECETA(Id_receta)

-- CITA_SERVICIO → CITA
ALTER TABLE CITA_SERVICIO
ADD FOREIGN KEY (Id_cita) REFERENCES CITA(Id_cita)

-- CITA_SERVICIO → SERVICIO
ALTER TABLE CITA_SERVICIO
ADD FOREIGN KEY (Id_servicio) REFERENCES SERVICIO(Id_servicio)

-- PAGO → CITA
ALTER TABLE PAGO
ADD FOREIGN KEY (Id_cita) REFERENCES CITA(Id_cita)

-- PAGO → DOCTOR
ALTER TABLE PAGO
ADD FOREIGN KEY (Id_Doctor) REFERENCES DOCTOR(Id_doctor)

-- BITACORA_CITA → CITA
ALTER TABLE BITACORA_CITA
ADD FOREIGN KEY (Id_cita) REFERENCES CITA(Id_cita)

-- BITACORA_CITA → RECEPCIONISTA
ALTER TABLE BITACORA_CITA
ADD FOREIGN KEY (Id_Recepcionista) REFERENCES RECEPCIONISTA(Id_Recepcionista)


--INSERCION DE DATOS
INSERT INTO PACIENTE (Nombre, Apellido_Paterno, Apellido_Materno, Curp, Telefono) VALUES
('Carlos',  'Ramírez',   'Soto',  'RASC900101HDFMTL09', '5551001001'),
('Laura',   'Mendoza',   'Ríos',  'MERL850215MDFNRS04', '5551001002'),
('Jorge',   'Gutiérrez', 'Vega',  'GUVJ780320HDFTRR07', '5551001003'),
('Ana',     'Torres',    'Leal',  'TOLA920510MDFRRN02', '5551001004')